# Generated by Django 2.1.1 on 2018-10-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=20)),
                ('alcholic', models.BooleanField(default=True)),
                ('ingridents', models.CharField(default='unknown', max_length=500)),
                ('alcholic_content', models.CharField(default='unknown', max_length=100)),
                ('location', models.CharField(default='unknown', max_length=30)),
                ('type', models.CharField(default='unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=20)),
                ('type', models.CharField(default='unknown', max_length=20)),
                ('description', models.CharField(default='unknown', max_length=100)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('ticket', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='bar',
            name='hours',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='bar',
            name='location',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
