# Generated by Django 2.1.1 on 2018-11-01 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_auto_20181009_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='bar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.Bar'),
        ),
    ]
