# Generated by Django 2.1.1 on 2018-11-01 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_menu_bar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('size', models.IntegerField()),
                ('total_amount', models.IntegerField(null=True)),
                ('current_ammount', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='bar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.Bar'),
        ),
        migrations.AddField(
            model_name='user',
            name='bar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.Bar'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='alcholic_content',
            field=models.CharField(default='unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='ingridents',
            field=models.CharField(default='unknown', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='location',
            field=models.CharField(default='unknown', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.Drink'),
        ),
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.Menu'),
        ),
    ]
