# Generated by Django 2.1.1 on 2018-11-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0004_auto_20181101_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='item',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='item',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
