# Generated by Django 2.1.1 on 2018-11-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0011_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
