# Generated by Django 2.1.1 on 2018-11-01 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0013_auto_20181101_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=20)),
                ('type', models.CharField(default='unknown', max_length=20)),
                ('description', models.CharField(default='unknown', max_length=100)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('ticket', models.BooleanField(default=False)),
                ('bar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.Bar')),
            ],
        ),
    ]
