# Generated by Django 2.1.1 on 2018-11-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0014_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='item',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
