# Generated by Django 2.1.1 on 2018-11-01 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0015_auto_20181101_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('size', models.IntegerField()),
                ('total_amount', models.IntegerField(null=True)),
                ('current_ammount', models.IntegerField(null=True)),
                ('drink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.Drink')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.Menu')),
            ],
        ),
    ]
