# Generated by Django 2.1.1 on 2018-11-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0016_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
