# Generated by Django 2.1.1 on 2018-11-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0016_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='item',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='item',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bar',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
