# Generated by Django 2.1.1 on 2018-11-02 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0017_auto_20181102_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=20)),
                ('type', models.CharField(default='unknown', max_length=20)),
                ('description', models.CharField(default='unknown', max_length=100)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('ticket', models.BooleanField(default=False)),
                ('bar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.Bar')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('size', models.IntegerField()),
                ('total_amount', models.IntegerField(null=True)),
                ('current_ammount', models.IntegerField(null=True)),
                ('drink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.Drink')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=20)),
                ('bar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.Bar')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=20)),
                ('bar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.Bar')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.Menu'),
        ),
    ]
