# Generated by Django 2.1.1 on 2018-11-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0017_auto_20181124_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bar',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
