# Generated by Django 2.1.1 on 2018-11-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0020_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bar',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
