# Generated by Django 2.1.2 on 2018-11-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0022_auto_20181124_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='drink',
        ),
        migrations.AddField(
            model_name='item',
            name='alcholic_content',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ingridents',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='subtype',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
