# Generated by Django 2.1.2 on 2018-11-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0023_auto_20181125_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
