# Generated by Django 2.1.2 on 2018-11-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0025_auto_20181125_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
