# Generated by Django 2.1.2 on 2018-11-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0027_auto_20181125_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='alcholic_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
