# Generated by Django 2.1.2 on 2018-11-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0029_auto_20181125_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='purchases',
            field=models.IntegerField(default=0),
        ),
    ]
