# Generated by Django 2.1.2 on 2018-11-26 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0034_auto_20181126_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Event Date'),
        ),
    ]
