# Generated by Django 2.1.2 on 2018-11-27 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0039_auto_20181126_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('size', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('type', models.CharField(default='', max_length=20)),
                ('subtype', models.CharField(default='', max_length=20)),
                ('amount_flag', models.BooleanField(default=True)),
                ('purchases', models.IntegerField(default=0)),
                ('ingridents', models.CharField(blank=True, default='', max_length=500)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('current_amount', models.IntegerField(blank=True, null=True)),
                ('alcholic_content', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.Menu')),
            ],
        ),
    ]
