# Generated by Django 2.1.2 on 2018-11-27 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0040_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Event Date'),
        ),
    ]
